# NumPy Arrays

## Sections:

1.  Creating Arrays
2.  Basic Data Types
3.  Indexing and Slicing
4.  Copies and Views
5.  Fancy Indexing
    

**python objects:** 

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [2]:
import numpy as np
np.__version__

'1.16.4'

In [0]:
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


**Why it is useful:** Memory-efficient container that provides fast numerical operations.

In [4]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

1000 loops, best of 3: 286 µs per loop


In [3]:
a = np.arange(1000)
%timeit a**2

The slowest run took 23.32 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 1.35 µs per loop


<a id = 'create'/>

# 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [0]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [0]:
#print dimensions

a.ndim

1

In [0]:
#shape

a.shape

(4,)

In [0]:
len(a)

4

In [0]:
# 2-D, 3-D....

b = np.array([[0, 1, 2], [3, 4, 5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [0]:
b.ndim

2

In [0]:
b.shape

(2, 3)

In [0]:
len(b) #returns the size of the first dimention

2

In [0]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [0]:
c.ndim

3

In [0]:
c.shape

(2, 2, 2)

** 1.2  Functions for creating arrays**

In [0]:
#using arrange function

# arange is an array-valued version of the built-in Python range function

a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [0]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [0]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [0]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [0]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [0]:
np.diag(a)   #Extract diagonal

array([1, 2, 3, 4])

In [0]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([0.98295737, 0.26102485, 0.49776355, 0.92326879])

In [0]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([-1.0792458 , -0.79263086, -0.28886266, -0.03030671])

<a id = 'types'/> 
# 2. Basic DataTypes

You may have noticed that, in some instances, array elements are displayed with a **trailing dot (e.g. 2. vs 2)**. This is due to a difference in the **data-type** used:

In [0]:
a = np.arange(10)

a.dtype

dtype('int32')

In [0]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [0]:
#The default data type is float for zeros and ones function

a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

**Other datatypes**

In [0]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [0]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [0]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

**For more details**

**https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html**

<a id = 'index'/>

# 3. Indexing and Slicing

**3.1 Indexing**

The items of an array can be accessed and assigned to the same way as other **Python sequences (e.g. lists)**:

In [0]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [0]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])

3


In [0]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [0]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [0]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [0]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

<a id = 'copy'/>
# 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use **np.may_share_memory()** to check if two arrays share the same memory block. 

**When modifying the view, the original array is modified as well:**

In [0]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [0]:
np.shares_memory(a, b)

True

In [0]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [0]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [0]:


a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [0]:
np.shares_memory(a, c)

False

In [0]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<a id = 'fancy'/>

# 5. Fancy Indexing

NumPy arrays can be indexed with slices, but also with boolean or integer arrays **(masks)**. This method is called **fancy indexing**. It creates copies not views.

**Using Boolean Mask**

In [7]:
a = np.random.randint(0, 20, 15)
a

array([ 0,  5, 15,  4, 12,  7,  2,  2,  7, 13, 10, 13, 14, 19,  2])

In [0]:
mask = (a % 2 == 0)

In [9]:
extract_from_a = a[mask]

extract_from_a

array([ 0,  4, 12,  2,  2, 10, 14,  2])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [10]:
a[mask] = -1
a

array([-1,  5, 15, -1, -1,  7, -1, -1,  7, 13, -1, 13, -1, 19, -1])